Repository projectsyn/component-xelon-csi, pull requests merged in 2023-01, with the labels that each got.

#2 Add support for configuring resource requests and limits
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/xelon-csi/xelon-csi/daemonset.yaml
  tests/golden/defaults/xelon-csi/xelon-csi/statefulset.yaml
  tests/golden/openshift/xelon-csi/xelon-csi/daemonset.yaml
  tests/golden/openshift/xelon-csi/xelon-csi/statefulset.yaml
Labels: enhancement

#3 Configure renovate to update the defaults.yaml dependencies
  class/defaults.yml
  renovate.json
Labels: enhancement

#4 Fix renovate regexManager versioningTemplate
  renovate.json
Labels: bug

#7 Update reference documentation
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: documentation

#6 Remove the volume expansion warning
  docs/modules/ROOT/pages/index.adoc
Labels: documentation

#8 Don't explicitly set `imagePullPolicy: IfNotPresent`
  component/main.jsonnet
  tests/golden/defaults/xelon-csi/xelon-csi/daemonset.yaml
  tests/golden/defaults/xelon-csi/xelon-csi/statefulset.yaml
  tests/golden/openshift/xelon-csi/xelon-csi/daemonset.yaml
  tests/golden/openshift/xelon-csi/xelon-csi/statefulset.yaml
Labels: change
